# Generated by Django 5.0.4 on 2024-05-28 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_wishlistmodel_remove_wishlistitem_wishlist_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='wishlistmodel',
            new_name='wishlist',
        ),
    ]
