# Generated by Django 5.0.4 on 2024-07-21 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_alter_wishlist_unique_together_wishlist_customer_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wishlist',
            old_name='Customer',
            new_name='customer',
        ),
        migrations.RenameField(
            model_name='wishlist',
            old_name='Product',
            new_name='product',
        ),
    ]
