# Generated by Django 5.0.4 on 2024-07-21 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_rename_customer_wishlist_customer_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='wishlist',
        ),
    ]
